#
# SPDX-FileCopyrightText: The LineageOS Project
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/tcl/Gflip6_TF

# Architecture
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a53

TARGET_USES_64_BIT_BINDER := true

# APEX
OVERRIDE_TARGET_FLATTEN_APEX := true

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := gflip6
TARGET_NO_BOOTLOADER := true

# Display
TARGET_SCREEN_DENSITY := 160

# Kernel
BOARD_BOOT_HEADER_VERSION := 2
BOARD_KERNEL_BASE := 0x40000000
BOARD_KERNEL_CMDLINE := bootopt=64S3,32S1,32S1 buildvariant=user
BOARD_KERNEL_PAGESIZE := 2048
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)
BOARD_KERNEL_IMAGE_NAME := Image
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
TARGET_KERNEL_CONFIG := Gflip6_TF_defconfig
TARGET_KERNEL_SOURCE := kernel/tcl/Gflip6_TF

# Kernel - prebuilt
TARGET_FORCE_PREBUILT_KERNEL := true
ifeq ($(TARGET_FORCE_PREBUILT_KERNEL),true)
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilts/kernel
TARGET_PREBUILT_DTB := $(DEVICE_PATH)/prebuilts/dtb.img
BOARD_MKBOOTIMG_ARGS += --dtb $(TARGET_PREBUILT_DTB)
endif

# Partitions
BOARD_FLASH_BLOCK_SIZE := 131072 # (BOARD_KERNEL_PAGESIZE * 64)
BOARD_BOOTIMAGE_PARTITION_SIZE := 25165824
BOARD_SUPER_PARTITION_SIZE := 9126805504
BOARD_SUPER_PARTITION_GROUPS := tcl_dynamic_partitions
BOARD_TCL_DYNAMIC_PARTITIONS_PARTITION_LIST := \
    system \
    vendor \
    product
BOARD_TCL_DYNAMIC_PARTITIONS_SIZE := 9122611200

# Platform
TARGET_BOARD_PLATFORM := mt6739

# Properties
TARGET_SYSTEM_PROP += $(DEVICE_PATH)/system.prop
TARGET_VENDOR_PROP += $(DEVICE_PATH)/vendor.prop
TARGET_PRODUCT_PROP += $(DEVICE_PATH)/product.prop
TARGET_SYSTEM_EXT_PROP += $(DEVICE_PATH)/system_ext.prop
TARGET_ODM_PROP += $(DEVICE_PATH)/odm.prop

# Recovery
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/rootdir/etc/fstab.enableswap
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

# TWRP
ifeq ($(WITH_TWRP),true)
TW_THEME := watch
TW_SCREEN_WIDTH := 240
TW_SCREEN_HEIGHT := 320
TW_CUSTOM_BATTERY := /sys/class/power_supply/battery
TW_BRIGHTNESS_PATH := /sys/class/leds/lcd-backlight/brightness
TW_MAX_BRIGHTNESS := 255
TW_DEFAULT_BRIGHTNESS := 128
TW_NO_SCREEN_BLANK := true
TW_USE_SYSTEM_BRIGHTNESS := true
TW_IGNORE_MAJOR_AXIS_0 := true
TW_CRYPTO_USE_SYSTEM_VOLD := true
TW_CRYPTO_MNT_POINT := /data
TW_CRYPTO_FS_TYPE := f2fs
TW_CRYPTO_REAL_BLKDEV := /dev/block/platform/bootdevice/by-name/userdata
TW_CRYPTO_MNT_DEV := /dev/block/platform/bootdevice/by-name/userdata
TW_CRYPTO_FS_OPTIONS := nosuid,nodev,noatime,discard,reserve_root=134217,resgid=1065,latemount,wait,check,quota,reservedsize=128M,formattable,resize,checkpoint=fs,fileencryption=aes-256-xts:aes-256-cts:v2,keydirectory=/metadata/vold/metadata_encryption
TW_CRYPTO_FS_FLAGS := 0x00000406
TW_CRYPTO_KEY_LOC := footer
TW_HAS_DOWNLOAD_MODE := true
TW_NO_REBOOT_BOOTLOADER := true
TW_USE_MODEL_HARDWARE_ID_FOR_DEVICE_KEYS := true
TW_INCLUDE_NTFS_3G := true
TW_INCLUDE_CRYPTO := true
TW_SDEXT_NO_EXT4 := true
TW_MTP_DEVICE := /dev/mtp_usb
TW_CRYPTO_ADD_RECOVERY_SCRIPT := true
TW_CRYPTO_ADD_BOOT_SCRIPT := true
TW_CRYPTO_ADD_DEVICE_KEYS_SCRIPT := true
TW_CRYPTO_ADD_DEVICE_KEYS_TO_BOOT_SCRIPT := true
TW_CRYPTO_ADD_DEVICE_KEYS_TO_RECOVERY_SCRIPT := true
TW_CRYPTO_ADD_DEVICE_KEYS_TO_SYSTEM_SCRIPT := true
TW_CRYPTO_ADD_DEVICE_KEYS_TO_VENDOR_SCRIPT := true
TW_CRYPTO_ADD_DEVICE_KEYS_TO_PRODUCT_SCRIPT := true
TW_CRYPTO_ADD_DEVICE_KEYS_TO_ODM_SCRIPT := true
TW_CRYPTO_ADD_DEVICE_KEYS_TO_SYSTEM_EXT_SCRIPT := true
TW_CRYPTO_ADD_DEVICE_KEYS_TO_METADATA_SCRIPT := true
TW_CRYPTO_ADD_DEVICE_KEYS_TO_VENDOR_BOOT_SCRIPT := true
TW_CRYPTO_ADD_DEVICE_KEYS_TO_INIT_BOOT_SCRIPT := true
TW_CRYPTO_ADD_DEVICE_KEYS_TO_RECOVERY_RAMDISK_SCRIPT := true
TW_CRYPTO_ADD_DEVICE_KEYS_TO_BOOT_RAMDISK_SCRIPT := true
TW_CRYPTO_ADD_DEVICE_KEYS_TO_SYSTEM_RAMDISK_SCRIPT := true
TW_CRYPTO_ADD_DEVICE_KEYS_TO_VENDOR_RAMDISK_SCRIPT := true
TW_CRYPTO_ADD_DEVICE_KEYS_TO_PRODUCT_RAMDISK_SCRIPT := true
TW_CRYPTO_ADD_DEVICE_KEYS_TO_ODM_RAMDISK_SCRIPT := true
TW_CRYPTO_ADD_DEVICE_KEYS_TO_SYSTEM_EXT_RAMDISK_SCRIPT := true
TW_CRYPTO_ADD_DEVICE_KEYS_TO_METADATA_RAMDISK_SCRIPT := true
TW_CRYPTO_ADD_DEVICE_KEYS_TO_VENDOR_BOOT_RAMDISK_SCRIPT := true
TW_CRYPTO_ADD_DEVICE_KEYS_TO_INIT_BOOT_RAMDISK_SCRIPT := true
endif

# Security patch level
VENDOR_SECURITY_PATCH := 2021-09-05

# Verified Boot
BOARD_AVB_ENABLE := true
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 3

# VINTF
DEVICE_MANIFEST_FILE += $(DEVICE_PATH)/manifest.xml
